FROM openjdk:8u212-jdk-stretch

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
    git bash ant wget subversion diffutils

# fetch and build renderer
RUN mkdir /workspace \
    && cd workspace \
    && git clone https://github.com/OpenNauticalChart/renderer.git \
    && cd renderer \
    && cd jsearch \
    && ant

RUN cd /workspace \
		&& svn co https://josm.openstreetmap.de/osmsvn/applications/editors/josm/plugins/seachart \
	  && cd seachart/jrender/ \
	  && ant

# create links for required jar files
RUN cd /workspace \
    && ln -s /workspace/renderer/jsearch/jsearch.jar jsearch.jar \
    && ln -s /workspace/seachart/jrender/jrender.jar jrender.jar

# deploy run script
COPY run.sh /usr/local/bin
RUN chmod +x /usr/local/bin/run.sh

# deploy render script
COPY jrender.sh /usr/local/bin
COPY jsearch.sh /usr/local/bin
COPY update.sh  /usr/local/bin

RUN chmod +x /usr/local/bin/*.sh

ENTRYPOINT ["/usr/local/bin/run.sh"]

CMD []
