#!/bin/bash

  # input files:
  #   osm/xapi.osm  - includes seamark extract from planet.osm3s_query
  #                   generated with overpass api osm3s_query
  #   osm/world.osm - includes backup of latest processed seamark extract
  #   tils/z/x/y    - collection of tiles generated by sea mark renderer
  #
  # output data:
  #   tils/z/x/y    - mix of old tiles and new generated tiles
  #   osm/world.osm - backup of osm seamark extract for CONSECUTIVE processing

  set -x

  echo "$(date) update: start " >> logging/log.txt

  cd /workspace

  # cleanup tmp directory
  rm -fr tmp/*

  # copy next.osm to working dir
  cp osm/xapi.osm next.osm

  # copy world.osm to working dir
  cp osm/world.osm  world.osm

  # start jsearch
  jsearch.sh

  # start jsearch
  jrender.sh

  # copy/backup osm extract for CONSECUTIVE processing
  mv next.osm osm/world.osm

  echo "$(date) update: ready " >> logging/log.txt
